## CREAT A 3 DATAFRAME USING DISNARY

In [13]:
import pandas

In [14]:
import pandas as pd

emplye = {"name" : ["aswin","RAVI","mohan"],
    "age": [21,32,24],
    "course" : ["AI","ML","DATA SCIENCE"],
    "perfomance" : ["good","average","okey"]}

In [15]:
pd.DataFrame(emplye)

    name  age        course perfomance
0  aswin   21            AI       good
1   RAVI   32            ML    average
2  mohan   24  DATA SCIENCE       okey

In [28]:
univercity_entrance_test_result = {
    "Roll No": [501,507,509,500],
    "Name": ["Aswin","kavin","ravi","mohan"],
    "Age": [20,21,24,22],
    "College": ["RVS College","KPR","PSG","Anna univercity"],
    "Course": ["BCA","B.COM","MCA","B.TECH"],
    "Semester": [6,4,3,5],
    "CGPA": [8.5,7.5,8.2,9.5],
    "City": ["Tirupur","coimbatore","salem","banglore"],
    "Attendance": ["92%","82%","72%","95%"],
    "Passed": ["Yes","NO","YES","YES"]
}

In [29]:
pd.DataFrame(data=univercity_entrance_test_result)

,Roll No,Name,Age,College,Course,Semester,CGPA,City,Attendance,Passed
0,501,Aswin,20,RVS College,BCA,6,8.5,Tirupur,92%,Yes
1,507,kavin,21,KPR,B.COM,4,7.5,coimbatore,82%,NO
2,509,ravi,24,PSG,MCA,3,8.2,salem,72%,YES
3,500,mohan,22,Anna univercity,B.TECH,5,9.5,banglore,95%,YES

In [36]:
data = {
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": [
        "Aswin", "Rahul", "Priya", "Karthik", "Meena",
        "Arun", "Divya", "Vijay", "Sneha", "Ajay"
    ],
    "age": [22, 25, 24, 27, 23, 26, 21, 29, 28, 24],
    "gender": [
        "Male", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male"
    ],
    "department": [
        "Data Analytics", "AI", "HR", "Finance", "Marketing",
        "Sales", "AI", "Data Analytics", "HR", "Finance"
    ],
    "salary": [
        35000, 50000, 32000, 45000, 38000,
        40000, 55000, 36000, 34000, 47000
    ],
    "experience": [1, 3, 2, 5, 2, 4, 1, 3, 2, 5],
    "city": [
        "Coimbatore", "Chennai", "Bangalore", "Hyderabad", "Mumbai",
        "Pune", "Delhi", "Coimbatore", "Chennai", "Bangalore"
    ],
    "performance_score": [85, 91, 78, 88, 82, 90, 95, 80, 76, 89],
    "is_full_time": [
        True, True, False, True, True,
        False, True, True, False, True
    ]
}

In [31]:
pd.DataFrame(data)

,employee_id,name,age,gender,department,salary,experience,city,performance_score,is_full_time
0,101,Aswin,22,Male,Data Analytics,35000,1,Coimbatore,85,True
1,102,Rahul,25,Male,AI,50000,3,Chennai,91,True
2,103,Priya,24,Female,HR,32000,2,Bangalore,78,False
3,104,Karthik,27,Male,Finance,45000,5,Hyderabad,88,True
4,105,Meena,23,Female,Marketing,38000,2,Mumbai,82,True
5,106,Arun,26,Male,Sales,40000,4,Pune,90,False
6,107,Divya,21,Female,AI,55000,1,Delhi,95,True
7,108,Vijay,29,Male,Data Analytics,36000,3,Coimbatore,80,True
8,109,Sneha,28,Female,HR,34000,2,Chennai,76,False
9,110,Ajay,24,Male,Finance,47000,5,Bangalore,89,True

In [33]:
data.get("salary")

[35000, 50000, 32000, 45000, 38000, 40000, 55000, 36000, 34000, 47000]

In [39]:
inside_data = data.items()
inside_data

dict_items([('employee_id', [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]), ('name', ['Aswin', 'Rahul', 'Priya', 'Karthik', 'Meena', 'Arun', 'Divya', 'Vijay', 'Sneha', 'Ajay']), ('age', [22, 25, 24, 27, 23, 26, 21, 29, 28, 24]), ('gender', ['Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male']), ('department', ['Data Analytics', 'AI', 'HR', 'Finance', 'Marketing', 'Sales', 'AI', 'Data Analytics', 'HR', 'Finance']), ('salary', [35000, 50000, 32000, 45000, 38000, 40000, 55000, 36000, 34000, 47000]), ('experience', [1, 3, 2, 5, 2, 4, 1, 3, 2, 5]), ('city', ['Coimbatore', 'Chennai', 'Bangalore', 'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Coimbatore', 'Chennai', 'Bangalore']), ('performance_score', [85, 91, 78, 88, 82, 90, 95, 80, 76, 89]), ('is_full_time', [True, True, False, True, True, False, True, True, False, True])])

In [40]:
pd.DataFrame(inside_data)

                   0                                                  1
0        employee_id  [101, 102, 103, 104, 105, 106, 107, 108, 109, ...
1               name  [Aswin, Rahul, Priya, Karthik, Meena, Arun, Di...
2                age           [22, 25, 24, 27, 23, 26, 21, 29, 28, 24]
3             gender  [Male, Male, Female, Male, Female, Male, Femal...
4         department  [Data Analytics, AI, HR, Finance, Marketing, S...
5             salary  [35000, 50000, 32000, 45000, 38000, 40000, 550...
6         experience                     [1, 3, 2, 5, 2, 4, 1, 3, 2, 5]
7               city  [Coimbatore, Chennai, Bangalore, Hyderabad, Mu...
8  performance_score           [85, 91, 78, 88, 82, 90, 95, 80, 76, 89]
9       is_full_time  [True, True, False, True, True, False, True, T...

In [45]:
pd.unique(data)

C:\Users\~A S W I N\AppData\Local\Temp\ipykernel_1880\175039508.py:1: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  pd.unique(data)

array(['employee_id', 'name', 'age', 'gender', 'department', 'salary',
       'experience', 'city', 'performance_score', 'is_full_time'],
      dtype=object)